[tool.robotpy-build.metadata]
name = "robotpy-wpiutil"
description = "Binary wrapper for FRC WPIUtil library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-wpiutil"
license = "BSD-3-Clause"
install_requires = []

[build-system]
requires = [
    "robotpy-build<2025.0.0b1,~=2025.0.0a8",
]

[tool.robotpy-build]
base_package = "wpiutil"
update_init = [
    "wpiutil",
    "wpiutil.log wpiutil._wpiutil.log",
    "wpiutil.sync wpiutil._wpiutil.sync",
    "wpiutil.wpistruct wpiutil._wpiutil.wpistruct",
]
scan_headers_ignore = [
    "fmt/*",
    "google/*",
    "wpi/*",
    "wpystruct_fns.h",
    "pb.h",
    "pb_common.h",
    "pb_decode.h",
    "pb_encode.h",
]

[tool.robotpy-build.wrappers."wpiutil"]
name = "wpiutil"
sources = [
    "wpiutil/src/main.cpp",
    "wpiutil/src/safethread_gil.cpp",
    "wpiutil/src/stacktracehook.cpp",
    "wpiutil/src/wpistruct/wpystruct_fns.cpp",
]
extra_includes = [
    "wpiutil/src/wpistruct",
    "wpiutil/src/type_casters",
]

generation_data = "gen"

[tool.robotpy-build.wrappers."wpiutil".maven_lib_download]
artifact_id = "wpiutil-cpp"
group_id = "edu.wpi.first.wpiutil"
repo_url = "https://frcmaven.wpi.edu/artifactory/development"
# repo_url = "https://frcmaven.wpi.edu/artifactory/development"
version = "2025.1.1-beta-3"

libs = ["wpiutil"]

[tool.robotpy-build.wrappers."wpiutil".autogen_headers]
# wpi
DataLog = "wpi/DataLog.h"
DataLogReader = "wpi/DataLogReader.h"
DataLogBackgroundWriter = "wpi/DataLogBackgroundWriter.h"
DataLogWriter = "wpi/DataLogWriter.h"
StackTrace = "wpi/StackTrace.h"
Synchronization = "wpi/Synchronization.h"
RawFrame = "wpi/RawFrame.h"

# wpi/sendable
Sendable = "wpi/sendable/Sendable.h"
SendableBuilder = "wpi/sendable/SendableBuilder.h"
#SendableHelper = "wpi/sendable/SendableHelper.h"
SendableRegistry = "wpi/sendable/SendableRegistry.h"

WPyStruct = "src/wpistruct/wpystruct_fns.h"

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_array_type_caster.h"
types = ["wpi::array"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_json_type_caster.h"
types = ["wpi::json"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_span_type_caster.h"
types = ["std::span"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_smallset_type_caster.h"
types = ["wpi::SmallSet"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_smallvector_type_caster.h"
types = ["wpi::SmallVector"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_smallvectorimpl_type_caster.h"
types = ["wpi::SmallVectorImpl"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_string_map_caster.h"
types = ["wpi::StringMap"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpi_ct_string_type_caster.h"
types = ["wpi::ct_string"]

[[tool.robotpy-build.wrappers."wpiutil".type_casters]]
header = "wpystruct.h"
types = ["WPyStruct"]